/**
* @copyright 2026 - Prazon
* @license MIT
*/
#pragma once
#include <stdint.h>

namespace P64::Resources
{
  // Generated by the editor's resource builder, defined in
  // <project>/src/p64/resourceTable.cpp. The asset manager invokes these
  // around the lazy load / free of any RESOURCE_INSTANCE entry so the
  // user-supplied onLoad/onUnload bodies run with the loaded blob cast to
  // their Data struct.
  //
  // Both calls tolerate `data == nullptr` and asset indices that don't
  // correspond to a resource (in which case they no-op). User code should
  // never call them directly.
  void callOnLoad(uint32_t assetIdx, void* data);
  void callOnUnload(uint32_t assetIdx, void* data);
}
